### ISSUE TITLE
A question about the loss named as "kld"

### ISSUE THREAD

**Issue by small-simon** [kailigo/pacl#3]
Hi Kai,

Could you give me some insights about the "kld" loss in the line attached below? 

https://github.com/kailigo/pacl/blob/6c15e806c7badaa42751d3d92864d1e3c91db68d/utils/loss.py#L356

I didn't find any explanations about this loss in your paper. 

To my understanding, it is somewhat similar to the entropy loss "_H_" defined in the MME paper. However, the entropy loss is also computed in the below line. 
 
https://github.com/kailigo/pacl/blob/6c15e806c7badaa42751d3d92864d1e3c91db68d/main.py#L366

Therefore, I am a bit curious about the meaning of "kld" loss in your codes.

Thank you!

**Comment by kailigo** [comment]
Hi. It is just a regularization, which has a tiny effect on the performance. You can get similar performance by removing it, i.e., removing the --kld store_sture option.

**Comment by small-simon** [comment]
Hi Kai,

Thanks for your quick response! 

I think such regularization might be proposed or utilized elsewhere. Could you give me some references like the one that you referenced?

Intuitively, if a loss is named as "kld", then one may relate this loss to the Kullback–Leibler divergence.

Thank you!

Best regards,
Simon
